### ISSUE TITLE
How to obtain the knowledge graph by using UMLS?

### ISSUE THREAD

**Issue by mk-runner** [xiaoman-zhang/KAD#1]
very cool work, I have some questions and I hope you can help me. How can I obtain the knowledge graph through UMLS? Entities can be easily obtained by Scispacy, but I don't know how to acquire the relationship between entities.

**Comment by xiaoman-zhang** [comment]
The UMLS can be downloaded from https://www.nlm.nih.gov/research/umls/licensedcontent/umlsknowledgesources.html. The full release includes the UMLS Metathesaurus, Semantic Network, etc.  You can download and analyze these files to get the knowledge graph. ( We will update the full A2_KEBERT/data/umls_kg.csv file later)

**Comment by Nikki-Gu** [comment]
很感谢你们的工作！关于knowledge graph还有个问题想要请教一下，UMLS里面的数据包含很多和胸片无关的条目，请问你们是如何筛选出需要的条目和knowledge graph的呢？期待回复，谢谢。
