### ISSUE TITLE
Question about the data processing phase

### ISSUE THREAD

**Issue by Roypic** [xiaoman-zhang/KAD#12]
Dear authors,

I'm tring to reimplement the whole process. However when deal with MIMIC-CXR datasets with data_process.sh script, I found that the caption.csv file is almost blanket. Should I rearrange the dataset( dicom to jpg, establish the image-txt croessponding csv) or there are already prepared ones? Thanks.

**Comment by rookiemmmm** [comment]
Hello, where did data_process.sh script come from? I can't find it.

**Comment by xiaoman-zhang** [comment]
That's in the google drive/ Baidu Cloud. `./A1_DATA/MIMIC-CXR/data_preprocess`

**Comment by rookiemmmm** [comment]
Okay, thank you very much！

**Comment by rookiemmmm** [comment]
Hi, I can't find radgraph_entity_graphes.json in ../A1_DATA/MIMIC-CXR/json_preprocess/

**Comment by xiaoman-zhang** [comment]
Hi, The file was too large and I ran out of space on Google Drive, so I uploaded it to Baidu Netdisk. https://pan.baidu.com/s/1rozuHHsducL2S0NX4Hs4Tg?pwd=7ncb  code: 7ncb

**Comment by rookiemmmm** [comment]
Okay，thank you.

**Comment by rookiemmmm** [comment]
I'm sorry, I can't find MRSTY.csv in ../A1_DATA/UMLS/.

**Comment by Roypic** [comment]
Me too, I also can't find  MRSTY.csv  anywhere.

**Comment by xiaoman-zhang** [comment]
upload to https://github.com/xiaoman-zhang/KAD/blob/main/A1_DATA/UMLS/MRSTY.csv

**Comment by Roypic** [comment]
Much appreciate.

**Comment by WangYijun-OUC** [comment]
> Hi, The file was too large and I ran out of space on Google Drive, so I uploaded it to Baidu Netdisk. https://pan.baidu.com/s/1rozuHHsducL2S0NX4Hs4Tg?pwd=7ncb code: 7ncb

Hi, author! the link is expired. Could you please provide another link? Thank you very much.
