### ISSUE TITLE
Google drive folder is empty

### ISSUE THREAD

**Issue by terryli710** [xiaoman-zhang/KAD#26]
Hello, I was unable to locate the model checkpoint weights in the Google Drive folder you shared. Could you please upload the weights? Unfortunately, I couldn't access the Baidu Drive link. Thanks a lot.

**Comment by hapstraid** [comment]
I confirm that the problem is still relevant.

**Comment by xiaoman-zhang** [comment]
Sorry for this.  I have updated the Google Drive folder with the model checkpoint weights. You can access them here: 
 [https://drive.google.com/drive/folders/1ArEgk-VNKZnXd5Fjkf6tiNA4YvBDZCCF?usp=sharing](https://drive.google.com/drive/folders/1ArEgk-VNKZnXd5Fjkf6tiNA4YvBDZCCF?usp=sharing)

**Comment by hapstraid** [comment]
Thank you very much! I especially thank you for your promptness and
responsiveness!

Sincerely,
Ilya
