### ISSUE TITLE
About the attention map

### ISSUE THREAD

**Issue by o0t1ng0o** [xiaoman-zhang/KAD#3]
Hi @chaoyi-wu @xiaoman-zhang ,

Thank you for sharing this code.
I am wondering how to obtain the attention maps in Figure 5 in your paper?
![image](https://github.com/xiaoman-zhang/KAD/assets/16815652/0fac8628-b8f9-418f-a974-00dfe96519d1)

Thanks.

**Comment by xiaoman-zhang** [comment]
To obtain the attention maps, we utilize the attention weights of the last multi-head attention layer. we have updated the 'plot_visualize_512.py' file in the './A3_CLIP' directory. This updated file includes the necessary code to generate the attention maps. Hope this will be helpful.
