### ISSUE TITLE
The Resnet50 weight loaded from checkpoint does not match the weight created by class ModelRes

### ISSUE THREAD

**Issue by lzf18** [xiaoman-zhang/KAD#4]
Hello,
I hope this message finds you well.  I wanted to express my sincere gratitude for the incredible work you and the team have put into this project.

But when I load the checkpoint you provided, I meet some problems.

**The code is as follows**:

import torch
checkpoint = torch.load('./KAD_Models/KAD_1024/best_valid.pt')
import sys
sys.path.append("./A3_CLIP/")
from models.clip_tqn import CLP_clinical, ModelRes, TQN_Model
image_encoder = ModelRes(res_base_model='resnet50')
image_encoder.load_state_dict(checkpoint['image_encoder'])

**The error message is as follows**:
![image](https://github.com/xiaoman-zhang/KAD/assets/55374333/ec6834be-9858-47cc-8e7a-248ee3760e8a)

May I ask if the checkpoint you provided is resnet50? Or is there a problem with my code somewhere?

Best regards.

**Comment by lzf18** [comment]
@chaoyi-wu @xiaoman-zhang

**Comment by xiaoman-zhang** [comment]
The checkpoints of KAD_512 and KAD_1024 are based on ''class ModelRes512'' in clip_tqn.py

**Comment by lzf18** [comment]
OK. Thank you so much for helping me resolve my problem! I'll close this issue.
