### ISSUE TITLE
Inference Performance wrong

### ISSUE THREAD

**Issue by laihaoran** [xiaoman-zhang/KAD#9]
There is no vit.py in models

**Comment by laihaoran** [comment]
I try to test the public model in Chest-Xray14. I load the Knowledge encoder and KAD model to test_chestxray14.py, downloading from google drive. Finally, the mean auc score is 0.5728, comparing the public paper is 0.789. Hope for your reply, thanks.

**Comment by xiaoman-zhang** [comment]
Could you provide more info? 1. Which model did you download? KAD-512 or KAD-1024. 2. Have you changed any code in test_chestxray14.py? 3. Did you use the official_test.csv provided in google drive?

**Comment by xiaoman-zhang** [comment]
> There is no vit.py in models

added

**Comment by laihaoran** [comment]
Thanks for your reply. I used KAD-512, which download from google drive. For konwlegde enocder, I also download from google drive. There is two problem in test_chestxray14.py, that no hyper-parameter named 'img_res' in test_chestxray14.py, and the resnet model used ModelRes512. So I correct them. 
By the way, could you provied the model of resolution 224, since the expeiment results of public parer is test in this.

**Comment by xiaoman-zhang** [comment]
1. I'm sorry that I forgot to add the model ModelRes512 in the clip_tqn.py, there is a little difference between ModelRes and ModelRes512. Maybe that's the reason for the performance mismatch.
2. I'll upload the model checkpoint of resolution 224 later.

**Comment by laihaoran** [comment]
Thanks for your reply. Since the model checkpoint can be loaded to ModelRes512 in my testing, I think the performance mismatch maybe in the other reaseon. Please check out again.

**Comment by xiaoman-zhang** [comment]
I've uploaded the model checkpoint for 'model-224' and re-evaluated it on the chest x-ray14' dataset. Everything appears to be right. Would you mind trying 'model-224' with the update code and checking if there are still any differences?

**Comment by laihaoran** [comment]
Thanks for your reply. I download the model-224 from google driver, and try to test the performance. The error rasied "RuntimeError: PytorchStreamReader failed reading file data/114: invalid header or archive is corrupted". I think it cause by file  corruption during uploading. Please check out again.

**Comment by xiaoman-zhang** [comment]
I re-uploaded the model, downloaded it and checked it, it should be fine. :)

**Comment by laihaoran** [comment]
Thanks for your reply. I download the model-224 from google driver, and test the performance, which achieve ChesetXray14 AUC  0.533. It confuse me deeply. Please ask if you have run the code yourself？

**Comment by xiaoman-zhang** [comment]
Sorry for that. The code uploaded is an organized version of my original codebase. I will debug it tonight and let you know after confirming that there is no problem.

**Comment by xiaoman-zhang** [comment]
Hello, I have tested it and there is no problem with the code. The performance mismatch is because I trained multiple versions of text encoders (with different initializations). The given checkpoint should be initialized by 'GanjinZero/UMLSBert_ENG', or you can use the model that I uploaded on hugging face 'xmcmic/Med-KEBERT'. Sorry for not checking carefully when push the codes.

**Comment by laihaoran** [comment]
Thanks for your reply. I used the hugging face 'xmcmic/Med-KEBERT' and test the performance of KAD224, which achieve ChesetXray14 AUC 0.782. Can your release the version that achieve 0.789 in your paper. Thank your very much.
